AllCops:
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'node_modules/**/*'
Documentation: # Disabling documentation cop
  Enabled: false
Metrics/LineLength:
  Max: 120
