require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe AccountsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Account. As you add validations to Account, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {{name: 'Simon',
                          surname: 'Simon',
                          email: 'simon@gmail.com',
                          password: '123456'}
  }

  let(:invalid_attributes) {{name: nil,
                          surname: 'Simon',
                          email: 'simon@gmail.com',
                          password: '12'}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccountsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Account.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      account = Account.create! valid_attributes
      get :show, params: {id: account.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end


  describe "GET #edit" do
    it "returns a success response" do
      account = Account.create! valid_attributes
      get :edit, params: {id: account.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end


  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'Sime',
                          surname: 'Sime'}
      }

      it "updates the requested account" do
        account = Account.create! valid_attributes
        put :update, params: {id: account.to_param, account: new_attributes}, session: valid_session
        account.reload
        expect(account.name).to include('Sime')
        expect(account.surname).to include('Sime')
      end

      it "redirects to the account" do
        account = Account.create! valid_attributes
        put :update, params: {id: account.to_param, account: valid_attributes}, session: valid_session
        expect(response).to redirect_to(account)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested account" do
      account = Account.create! valid_attributes
      expect {
        delete :destroy, params: {id: account.to_param}, session: valid_session
      }.to change(Account, :count).by(-1)
    end

    it "redirects to the accounts list" do
      account = Account.create! valid_attributes
      delete :destroy, params: {id: account.to_param}, session: valid_session
      expect(response).to redirect_to(accounts_url)
    end
  end

end
